services:
  rtmp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1935:1935
      - 8088:8088
    volumes:
      - ./hls:/mnt/hls
    container_name: rtmp_server

  auth:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    volumes:
      - ./server:/server
    container_name: auth_server
