services:
  rtmp:
    image: murderousone/nginx-ffmpeg-rtmp:ubuntu-latest
    restart: unless-stopped
    networks:
      - local_network
    stdin_open: true
    tty: true
    ports:
      - 447:447
      - 1935:1935
    volumes:
      - mnt:/mnt
      - ./conf:/usr/local/nginx/conf/
    container_name: rtmp_server

  auth:
    build:
      context: server
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - local_network
    volumes:
      - mnt:/mnt
      - ./server:/server
    container_name: auth_server

volumes:
  mnt:
    driver: local
    driver_opts:
      type: none,
      o: bind
      device: ./mnt
  nginxconfig:

networks:
  local_network:
    driver: bridge