server {
    listen 80;
    server_name rtmp.livespark.local;
    client_max_body_size 20M;
    root /usr/share/nginx/html;
    index index.html;
}

server {
		listen 80;
		server_name play.livespark.local;

		client_body_timeout 10;
	    client_max_body_size 10m;

		# Serve HLS fragments
		location /hls {
			types {
				application/vnd.apple.mpegurl m3u8;
				video/mp2t ts;
				video/mp4 mp4;
				video/x-flv flv;
			}

			root /mnt;

			# CORS setup
			add_header 'Access-Control-Allow-Origin' '*' always;
			add_header 'Access-Control-Expose-Headers' 'Content-Length';

			# allow CORS preflight requests
			if ($request_method = 'OPTIONS') {
				add_header 'Access-Control-Allow-Origin' '*';
				add_header 'Access-Control-Max-Age' 1728000;
				add_header 'Content-Type' 'text/plain charset=UTF-8';
				add_header 'Content-Length' 0;
				return 204;
			}
		}
	}