database:
  database1:
    host: localhost:5432
    name: db-dev
    username: postgres
    password: password
    default: 1
    
  database2:
    host: localhost:5432
    name: db-prod
    username: postgres
    password: password
    default: 0