user www-data;
rtmp_auto_push on;
worker_processes  auto;
#error_log  logs/error.log;

events {
    worker_connections  4096;
}

# RTMP configuration
rtmp {
    server {
        listen 1935;
        
        #ping 30s;
        notify_method get;
        chunk_size 4096;

        application live {
            live on;
            #allow publish all;
            allow play all;

            on_publish http://auth_server:3030/auth;

            hls on;
            hls_nested on;
            hls_fragment 3;
            hls_playlist_length 600;
            hls_path /mnt/hls;
            hls_variant _src BANDWIDTH=4096000; # Source bitrate, source resolution
            hls_variant _hd720 BANDWIDTH=2048000; # High bitrate, HD 720p resolution
            hls_variant _mid BANDWIDTH=448000; # Medium bitrate, SD resolution
            hls_cleanup off;
        }
    }
}
